name: Release
on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:

jobs:
  docker:
    name: Build ${{ github.repository }} Docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Prepare for tag
        if: startsWith(github.ref, 'refs/tags/v')
        id: prep
        run: |
          echo "tags=s4m3l0/${{ github.repository }}:latest,s4m3l0/${{ github.repository }}:${GITHUB_REF/refs\/tags\//},ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest,ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
      - name: Image digest
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Build for non-tag
        if: startsWith(github.ref, 'refs/tags/v') == false
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
